name: Deploy to VM

on:
  push:
    branches:
      - product

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: |
            ${{ secrets.SERVER_SSH_KEY }}
            ${{ secrets.GIT_SSH_KEY }}

      - name: Add SSH key to known hosts
        run: |
          ssh-keyscan -H 164.92.101.253 >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh root@164.92.101.253 "cd /var/www/html/dolibarr && git pull origin main && sudo systemctl restart apache2 && sudo systemctl status apache2"
